### ISSUE TITLE
Product page: Uncaught ReferenceError - krona_coins_change is not defined

### ISSUE THREAD

**Issue by getdatakick** [eschiendorfer/genzo_krona#8]
In bleeding edge version of krona I get following error:

```
krona-loyalty.js:6 Uncaught ReferenceError: krona_coins_change is not defined
    at HTMLDocument.<anonymous> (krona-loyalty.js:6)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at Function.ready (jquery-1.11.0.min.js:2)
    at HTMLDocument.K (jquery-1.11.0.min.js:2)
```
Content of krna-loyalty.js:

```
$(document).ready(function() {

    // Show Loyalty Points on Product Page

    var price;
    var coins_change = krona_coins_change; <---------- ERROR
    var coins_conversion = krona_coins_conversion;
    var coins_in_cart = krona_coins_in_cart;
```
This javascript error breaks the rest of the js included on the page, not related to krona itself. I suggest to either 
- check if variable is set in window object:`if (window.krona_coins_change)`
- or ensure that variables are always defined, if krona-loyalty.js file is included in the header. This is not the case at the moment due to [this](https://github.com/eschiendorfer/genzo_krona/blob/4a5c61ddbd8227644b9015a02014589f3c022c28/genzo_krona.php#L651)

**Comment by eschiendorfer** [comment]
Thx for the report! I have made a small change: https://github.com/eschiendorfer/genzo_krona/commit/4b052031537b808cf5e67a8513c3a583fb9a1fc0 Does this fix the issue?
